feat: fix complete interface, change resp to res, improve test coverage, add exists to buckets
nitrictech/dart-sdk pull request #23
Opened 2024-03-14 11:00 UTC by HomelessDinosaur

- fix message complete interface
 - change resp to res
 - add exists to buckets
 - add file event workers
 - improve unit tests, and coverage

2024-03-19 22:28 UTC, davemooreuws approved these changes

2024-04-18 02:01 UTC, tjholm commented on lib/src/resources/websocket.dart
> +      final channel = createClientChannelFromEnvVar();
should we be using shared or even a singleton channel here to maximise channel reuse?

Creating dedicated channels could lead to performance problems for larger functions, or when running on smaller infrastructure.

https://grpc.io/docs/guides/performance/

2024-04-19 03:12 UTC, tjholm requested changes
Remove OIDC rule from example

2024-04-22 00:33 UTC, tjholm approved these changes

2024-04-22 00:55 UTC, merged